### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [Artifex-Latronis/theScoop#5]
You did a really nice job on your project. Glad to see you put the functionality of each endpoint below the routes area. Also, each function looks good and all of the tests pass. Lastly, nice job using the built in functions to make your work a little easier. Just make sure next time you upload all of your files and not just the ones you worked on. Keep up the good work.

**Comment by Artifex-Latronis** [comment]
Thanks for the feedback!
